---

- hosts: all
  become: yes

  tasks:

    - name: "ALTER TABLE `rights` ADD `restriction` INTEGER"
      community.mysql.mysql_query:
        login_db: "{{ atom_db }}"
        query: "ALTER TABLE `rights` ADD `restriction` INTEGER"
