---

- hosts: all
  become: yes

  tasks:
    - name: install python3-mysqldb
      apt:
        pkg:
        - python3-mysqldb

    - name: "Dumping {{ atom_db }} database from localhost"
      community.mysql.mysql_db:
        state: dump
        name: "{{ atom_db }}"
        target: "{{ db_dump_file }}"
