---

- hosts: all
  become: yes

  tasks:

    - name: "/usr/bin/php{{ php_version }} -d memory_limit=-1 symfony cc"
      expect:
        chdir: "/usr/share/nginx/atom"
        command: "/usr/bin/php{{ php_version }} -d memory_limit=-1 symfony cc"
        echo: true
        responses:
          (?i)\(y\/N\): y
      register: output
      failed_when: false
    - debug: var=output.stdout_lines

    - name: set ownership /usr/share/nginx/atom
      file:
        path: /usr/share/nginx/atom
        owner: www-data
        group: www-data
        recurse: yes

    - name: restart fpm
      systemd:
        state: restarted
        name: "php{{ php_version }}-fpm"

    - name: start atom-worker
      systemd:
        state: started
        name: atom-worker
        daemon_reload: true
        enabled: true

