---

- hosts: all
  become: yes

  roles:
    - geerlingguy.php-mysql
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.mysql
    - geerlingguy.java
    - geerlingguy.elasticsearch
    - geerlingguy.composer
    - geerlingguy.certbot

  pre_tasks:
    - name: add ES_JAVA_OPTS to /etc/default/elasticsearch
      lineinfile: 
        line: "ES_JAVA_OPTS=-Djava.io.tmpdir=/var/lib/elasticsearch/tmp"
        path: /etc/default/elasticsearch
        create: true

    - name: install packages
      apt:
        pkg:
          - nginx
          - gearman-job-server
          - fop
          - libsaxon-java
          - imagemagick
          - ghostscript
          - poppler-utils
          - ffmpeg
          - node-less

  handlers:
    - name: restart webserver
      systemd:
        state: restarted
        name: nginx

