---
- name: Open HTTP/HTTPS ports
  hosts: all
  become: yes
  gather_facts: yes

  tasks:

  - name: open HTTP port 80
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "80"
      jump: ACCEPT
      action: insert
      state: present
    notify: save iptables

  - name: open HTTP port 443
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "443"
      jump: ACCEPT
      action: insert
      state: present
    notify: save iptables

  handlers:
    - name: save iptables
      shell: "/usr/sbin/iptables-save > /etc/iptables/rules.v4"

