---

- hosts: all
  become: yes

  tasks:

    - name: "run propel:build-nested-set"
      command: "/usr/bin/php{{ php_version }} -d memory_limit=-1 symfony propel:build-nested-set " 
      args:
        chdir: "/usr/share/nginx/atom"
      register: output

    - debug: var=output.stdout_lines

