---

- hosts: all
  become: yes

  tasks:

    - name: remove PDF line in /etc/ImageMagick-6/policy.xml 
      lineinfile:
        line: '  <policy domain="coder" rights="none" pattern="PDF" />'
        path: /etc/ImageMagick-6/policy.xml 
        state: absent


    - name: "run digitalobject:regen-derivatives"
      expect:
        command: "/usr/bin/php{{ php_version }} -d memory_limit=-1 symfony digitalobject:regen-derivatives "
        echo: true
        timeout: null
        chdir: "/usr/share/nginx/atom"
        responses:
          (?i).*\(y\/N\): y
      register: output
      failed_when: '"Done!" not in output.stdout'

    - debug: var=output.stdout_lines

